version: "3.9"

services:
  # --------------------------
  # Web Application (Flask)
  # --------------------------
  webapp:
    build: ./web
    container_name: flask_webapp
    expose:
      - "5000"
    restart: always

  # --------------------------
  # Local Git Server (Gitea)
  # --------------------------
  gitea:
    image: gitea/gitea:latest
    container_name: gitea_server
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea/data:/data
    ports:
      - "3000:3000"   # UI
      - "2222:22"     # SSH
    restart: always

  # --------------------------
  # NGINX Reverse Proxy
  # --------------------------
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    depends_on:
      - webapp
      - gitea
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
